# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GET_MAP.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rGET_MAP.proto\"\x1a\n\nMapRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"4\n\x0bMapResponse\x12\x0b\n\x03\x63ol\x18\x01 \x01(\x05\x12\x0b\n\x03row\x18\x02 \x01(\x05\x12\x0b\n\x03map\x18\x03 \x01(\t2,\n\x03Map\x12%\n\x06GetMap\x12\x0b.MapRequest\x1a\x0c.MapResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GET_MAP_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MAPREQUEST._serialized_start=17
  _MAPREQUEST._serialized_end=43
  _MAPRESPONSE._serialized_start=45
  _MAPRESPONSE._serialized_end=97
  _MAP._serialized_start=99
  _MAP._serialized_end=143
# @@protoc_insertion_point(module_scope)
