# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GET_COMMANDS.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12GET_COMMANDS.proto\"\x1e\n\x08RoverNum\x12\x12\n\nrover_name\x18\x01 \x01(\t\"\x1c\n\x08\x43ommands\x12\x10\n\x08\x63ommands\x18\x01 \x01(\t28\n\rRoverCommands\x12\'\n\rGetRoverMoves\x12\t.RoverNum\x1a\t.Commands\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GET_COMMANDS_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROVERNUM._serialized_start=22
  _ROVERNUM._serialized_end=52
  _COMMANDS._serialized_start=54
  _COMMANDS._serialized_end=82
  _ROVERCOMMANDS._serialized_start=84
  _ROVERCOMMANDS._serialized_end=140
# @@protoc_insertion_point(module_scope)
