# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import GET_SERIAL_pb2 as GET__SERIAL__pb2


class SerialStub(object):
    """define serial service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSerial = channel.unary_unary(
                '/Serial/GetSerial',
                request_serializer=GET__SERIAL__pb2.PlaceHolder.SerializeToString,
                response_deserializer=GET__SERIAL__pb2.SerialNumber.FromString,
                )


class SerialServicer(object):
    """define serial service
    """

    def GetSerial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SerialServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSerial': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSerial,
                    request_deserializer=GET__SERIAL__pb2.PlaceHolder.FromString,
                    response_serializer=GET__SERIAL__pb2.SerialNumber.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Serial', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Serial(object):
    """define serial service
    """

    @staticmethod
    def GetSerial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Serial/GetSerial',
            GET__SERIAL__pb2.PlaceHolder.SerializeToString,
            GET__SERIAL__pb2.SerialNumber.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
