# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import GET_COMMANDS_pb2 as GET__COMMANDS__pb2


class RoverCommandsStub(object):
    """define rover command service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRoverMoves = channel.unary_unary(
                '/RoverCommands/GetRoverMoves',
                request_serializer=GET__COMMANDS__pb2.RoverNum.SerializeToString,
                response_deserializer=GET__COMMANDS__pb2.Commands.FromString,
                )


class RoverCommandsServicer(object):
    """define rover command service
    """

    def GetRoverMoves(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoverCommandsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRoverMoves': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRoverMoves,
                    request_deserializer=GET__COMMANDS__pb2.RoverNum.FromString,
                    response_serializer=GET__COMMANDS__pb2.Commands.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'RoverCommands', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RoverCommands(object):
    """define rover command service
    """

    @staticmethod
    def GetRoverMoves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/RoverCommands/GetRoverMoves',
            GET__COMMANDS__pb2.RoverNum.SerializeToString,
            GET__COMMANDS__pb2.Commands.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
