# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GET_SERIAL.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10GET_SERIAL.proto\"#\n\x0bPlaceHolder\x12\x14\n\x0cplace_holder\x18\x01 \x01(\t\"!\n\x0cSerialNumber\x12\x11\n\tserial_no\x18\x01 \x01(\t24\n\x06Serial\x12*\n\tGetSerial\x12\x0c.PlaceHolder\x1a\r.SerialNumber\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'GET_SERIAL_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLACEHOLDER._serialized_start=20
  _PLACEHOLDER._serialized_end=55
  _SERIALNUMBER._serialized_start=57
  _SERIALNUMBER._serialized_end=90
  _SERIAL._serialized_start=92
  _SERIAL._serialized_end=144
# @@protoc_insertion_point(module_scope)
