# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POST_STATUS.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11POST_STATUS.proto\"0\n\rMessageStatus\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\x05\"$\n\x15\x41\x63knowledgementStatus\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2E\n\x0bRoverStatus\x12\x36\n\nSendStatus\x12\x0e.MessageStatus\x1a\x16.AcknowledgementStatus\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'POST_STATUS_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGESTATUS._serialized_start=21
  _MESSAGESTATUS._serialized_end=69
  _ACKNOWLEDGEMENTSTATUS._serialized_start=71
  _ACKNOWLEDGEMENTSTATUS._serialized_end=107
  _ROVERSTATUS._serialized_start=109
  _ROVERSTATUS._serialized_end=178
# @@protoc_insertion_point(module_scope)
