# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import POST_PIN_pb2 as POST__PIN__pb2


class PINStub(object):
    """define PIN service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendPin = channel.unary_unary(
                '/PIN/SendPin',
                request_serializer=POST__PIN__pb2.Pin.SerializeToString,
                response_deserializer=POST__PIN__pb2.Acknowledgement.FromString,
                )


class PINServicer(object):
    """define PIN service
    """

    def SendPin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PINServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendPin': grpc.unary_unary_rpc_method_handler(
                    servicer.SendPin,
                    request_deserializer=POST__PIN__pb2.Pin.FromString,
                    response_serializer=POST__PIN__pb2.Acknowledgement.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PIN', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PIN(object):
    """define PIN service
    """

    @staticmethod
    def SendPin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/PIN/SendPin',
            POST__PIN__pb2.Pin.SerializeToString,
            POST__PIN__pb2.Acknowledgement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
