# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: POST_PIN.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ePOST_PIN.proto\"\x12\n\x03Pin\x12\x0b\n\x03pin\x18\x01 \x01(\t\"\x1e\n\x0f\x41\x63knowledgement\x12\x0b\n\x03\x61\x63k\x18\x01 \x01(\t2*\n\x03PIN\x12#\n\x07SendPin\x12\x04.Pin\x1a\x10.Acknowledgement\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'POST_PIN_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PIN._serialized_start=18
  _PIN._serialized_end=36
  _ACKNOWLEDGEMENT._serialized_start=38
  _ACKNOWLEDGEMENT._serialized_end=68
  _PIN._serialized_start=70
  _PIN._serialized_end=112
# @@protoc_insertion_point(module_scope)
